# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-21 01:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id_ambiente', models.AutoField(db_column='id_ambiente', primary_key=True, serialize=False)),
                ('nombre_ambiente', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'AMBIENTE',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.AutoField(db_column='id_curso', primary_key=True, serialize=False)),
                ('cod_curso', models.CharField(blank=True, max_length=3, null=True)),
                ('nombre_curso', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'CURSO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CursoFuncionario',
            fields=[
                ('id_cursofuncionario', models.AutoField(db_column='id_cursofuncionario', primary_key=True, serialize=False)),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitacion.Curso')),
            ],
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id_etapa', models.AutoField(db_column='id_etapa', primary_key=True, serialize=False)),
                ('cod_etapa', models.CharField(blank=True, max_length=3, null=True)),
                ('nombre_etapa', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'ETAPA',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id_funcionario', models.AutoField(db_column='id_funcionario', primary_key=True, serialize=False)),
                ('cod_funcionario', models.CharField(blank=True, max_length=3, null=True)),
                ('nombre_funcionario', models.CharField(blank=True, max_length=100, null=True)),
                ('id_curso', models.ForeignKey(db_column='id_curso', on_delete=django.db.models.deletion.CASCADE, to='capacitacion.Curso')),
            ],
            options={
                'db_table': 'FUNCIONARIO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id_local', models.AutoField(db_column='id_local', primary_key=True, serialize=False)),
                ('nombre_local', models.CharField(blank=True, max_length=300, null=True)),
                ('tipo_via', models.CharField(blank=True, max_length=300, null=True)),
                ('nombre_via', models.CharField(blank=True, max_length=300, null=True)),
                ('referencia', models.CharField(blank=True, max_length=300, null=True)),
                ('n_direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('km_direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('mz_direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('lote_direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('piso_direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('telefono_local_fijo', models.CharField(blank=True, max_length=10, null=True)),
                ('telefono_local_celular', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_inicio', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_fin', models.CharField(blank=True, max_length=100, null=True)),
                ('turno_uso_local', models.CharField(blank=True, max_length=100, null=True)),
                ('capacidad_local', models.IntegerField(blank=True, null=True)),
                ('funcionario_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('funcionario_email', models.CharField(blank=True, max_length=100, null=True)),
                ('funcionario_telefono', models.CharField(blank=True, max_length=100, null=True)),
                ('funcionario_celular', models.CharField(blank=True, max_length=100, null=True)),
                ('responsable_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('responsable_email', models.CharField(blank=True, max_length=100, null=True)),
                ('responsable_telefono', models.CharField(blank=True, max_length=100, null=True)),
                ('responsable_celular', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'LOCAL',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LocalAmbiente',
            fields=[
                ('id_localambiente', models.AutoField(db_column='id_localambiente', primary_key=True, serialize=False)),
                ('cantidad_disponible', models.IntegerField()),
                ('cantidad_utilizar', models.IntegerField()),
                ('mesas_cant', models.IntegerField(blank=True, null=True)),
                ('sillas_cant', models.IntegerField(blank=True, null=True)),
                ('carpindividuales_cant', models.IntegerField(blank=True, null=True)),
                ('carpbipersonales_cant', models.IntegerField(blank=True, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('n_piso', models.IntegerField(blank=True, null=True)),
                ('capacidad', models.IntegerField(blank=True, null=True)),
                ('puerta_chapa', models.IntegerField(blank=True, null=True)),
                ('puerta_pestillocandado', models.IntegerField(blank=True, null=True)),
                ('puerta_notiene', models.IntegerField(blank=True, null=True)),
                ('sshh', models.IntegerField(blank=True, null=True)),
                ('alumbrado', models.IntegerField(blank=True, null=True)),
                ('pizarra_acrilica', models.IntegerField(blank=True, null=True)),
                ('pizarra_cemento', models.IntegerField(blank=True, null=True)),
                ('proyector', models.IntegerField(blank=True, null=True)),
                ('computadora', models.IntegerField(blank=True, null=True)),
                ('acceso_internet', models.IntegerField(blank=True, null=True)),
                ('id_ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitacion.Ambiente')),
                ('id_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitacion.Local')),
            ],
            options={
                'db_table': 'LOCAL_AMBIENTE',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ubigeo',
            fields=[
                ('ubigeo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('ccdd', models.CharField(blank=True, max_length=2, null=True)),
                ('ccpp', models.CharField(blank=True, max_length=2, null=True)),
                ('ccdi', models.CharField(blank=True, max_length=2, null=True)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('provincia', models.CharField(blank=True, max_length=100, null=True)),
                ('distrito', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'MAE_UBIGEO',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='local',
            name='ambientes',
            field=models.ManyToManyField(through='capacitacion.LocalAmbiente', to='capacitacion.Ambiente'),
        ),
        migrations.AddField(
            model_name='local',
            name='id_curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitacion.Curso'),
        ),
        migrations.AddField(
            model_name='local',
            name='ubigeo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitacion.Ubigeo'),
        ),
        migrations.AddField(
            model_name='cursofuncionario',
            name='id_funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitacion.Funcionario'),
        ),
        migrations.AddField(
            model_name='curso',
            name='etapa',
            field=models.ForeignKey(db_column='id_etapa', on_delete=django.db.models.deletion.CASCADE, to='capacitacion.Etapa'),
        ),
        migrations.AddField(
            model_name='curso',
            name='funcionarios',
            field=models.ManyToManyField(through='capacitacion.CursoFuncionario', to='capacitacion.Funcionario'),
        ),
    ]
