# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-21 01:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capacitacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursofuncionario',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='cursofuncionario',
            table='CURSO_FUNCIONARIO',
        ),
    ]
