# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-21 12:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capacitacion', '0002_auto_20161120_2053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='etapa',
            new_name='id_etapa',
        ),
    ]
