# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-22 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitacion', '0003_auto_20161121_0755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='localambiente',
            old_name='alumbrado',
            new_name='aireacondicionado',
        ),
        migrations.AddField(
            model_name='localambiente',
            name='alumbrado_electrico',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='localambiente',
            name='ventiladores',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
