# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-23 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitacion', '0005_auto_20161122_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='cantidad_usar_aulas',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
