# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-24 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitacion', '0008_auto_20161124_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='x',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='local',
            name='y',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
