# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-25 02:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capacitacion', '0009_auto_20161124_1336'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cursocriterio',
            unique_together=set([('id_curso', 'id_criterio')]),
        ),
    ]
