# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-28 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitacion', '0013_auto_20161128_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='cantidad_disponible_computo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='local',
            name='cantidad_total_computo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='local',
            name='cantidad_usar_computo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
