# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-30 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitacion', '0016_auto_20161130_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='pea',
            name='id_convocatoriacargo',
            field=models.CharField(blank=True, db_column='id_convocatoriacargo', max_length=4, null=True),
        ),
    ]
