# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-30 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitacion', '0017_pea_id_convocatoriacargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pea',
            name='zona',
            field=models.CharField(blank=True, db_column='zona', max_length=5, null=True),
        ),
    ]
