# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-30 15:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capacitacion', '0018_pea_zona'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pea_aula',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='pea_aula',
            table='PEA_AULA',
        ),
    ]
