# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-01 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitacion', '0020_local_zona_ubicacion_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='especifique_otros',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
