# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-05 05:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capacitacion', '0021_local_especifique_otros'),
    ]

    operations = [
        migrations.CreateModel(
            name='PEA_ASISTENCIA',
            fields=[
                ('id_asistencia', models.AutoField(primary_key=True, serialize=False)),
                ('marcacion', models.DateTimeField()),
                ('id_peaaula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitacion.PEA_AULA')),
            ],
            options={
                'db_table': 'PEA_ASISTENCIA',
                'managed': True,
            },
        ),
    ]
