# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-05 23:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capacitacion', '0023_auto_20161205_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pea_asistencia',
            name='id_peaaula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peaaulas', to='capacitacion.PEA_AULA'),
        ),
    ]
