# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-06 00:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capacitacion', '0025_auto_20161205_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pea_aula',
            name='id_pea',
            field=models.ForeignKey(db_column='id_pea', on_delete=django.db.models.deletion.CASCADE, related_name='peas', to='capacitacion.PEA'),
        ),
    ]
